-- Remove the ARTIFICER class and its subclasses from the enums.
-- No rows use these values, so no data migration is needed. Postgres cannot
-- drop an enum value in place, so each enum is recreated without them.

-- 1. Recreate the Classes enum without ARTIFICER.
ALTER TYPE "Classes" RENAME TO "Classes_old";

CREATE TYPE "Classes" AS ENUM ('BARBARIAN', 'BARD', 'CLERIC', 'DRUID', 'FIGHTER', 'MONK', 'PALADIN', 'RANGER', 'ROGUE', 'SORCERER', 'WARLOCK', 'WIZARD');

ALTER TABLE "Character" ALTER COLUMN "className" TYPE "Classes" USING ("className"::text::"Classes");
ALTER TABLE "Spell" ALTER COLUMN "classes" TYPE "Classes"[] USING ("classes"::text[]::"Classes"[]);

DROP TYPE "Classes_old";

-- 2. Recreate the Subclasses enum without the Artificer subclasses
--    (ALCHEMIST, ARMORER, ARTILLERIST, BATTLE_SMITH).
ALTER TYPE "Subclasses" RENAME TO "Subclasses_old";

CREATE TYPE "Subclasses" AS ENUM ('PATH_OF_THE_BERSERKER', 'PATH_OF_THE_WILD_HEART', 'PATH_OF_THE_ZEALOT', 'PATH_OF_THE_WORLD_TREE', 'OOTDL_HERCULEAN_PATH', 'COLLEGE_OF_DANCE', 'COLLEGE_OF_LORE', 'COLLEGE_OF_VALOR', 'COLLEGE_OF_GLAMOUR', 'OOTDL_COLLEGE_OF_EPIC_POETRY', 'LIFE_DOMAIN', 'LIGHT_DOMAIN', 'WAR_DOMAIN', 'TRICKERY_DOMAIN', 'OOTDL_PROPHECY_DOMAIN', 'CIRCLE_OF_THE_LAND', 'CIRCLE_OF_THE_MOON', 'CIRCLE_OF_THE_SEA', 'CIRCLE_OF_THE_STARS', 'OOTDL_CIRCLE_OF_SACRIFICE', 'OOTDL_CIRCLE_OF_THE_WYRM', 'BATTLE_MASTER', 'CHAMPION', 'ELDRITCH_KNIGHT', 'PSI_WARRIOR', 'OOTDL_DRAGON_KNIGHT', 'OOTDL_HOPLITE', 'WAY_OF_THE_OPEN_HAND', 'WAY_OF_SHADOW', 'WAY_OF_THE_ELEMENTS', 'WAY_OF_MERCY', 'OOTDL_WARRIOR_OF_THE_SHIELD', 'OATH_OF_DEVOTION', 'OATH_OF_GLORY', 'OATH_OF_THE_ANCIENTS', 'OATH_OF_VENGEANCE', 'OOTDL_OATH_OF_THE_DRAGONLORD', 'HUNTER', 'BEAST_MASTER', 'GLOOM_STALKER', 'FEY_WANDERER', 'OOTDL_AMAZON', 'THIEF', 'ASSASSIN', 'ARCANE_TRICKSTER', 'SOULKNIFE', 'OOTDL_ODYSSEAN', 'DRACONIC', 'WILD_MAGIC', 'ABERRANT', 'CLOCKWORK', 'OOTDL_DIVINE_SORCERY', 'THE_ARCHFEY', 'THE_FIEND', 'THE_GREAT_OLD_ONE', 'THE_CELESTIAL', 'OOTDL_THE_FATES', 'SCHOOL_OF_EVOCATION', 'SCHOOL_OF_ABJURATION', 'SCHOOL_OF_ILLUSION', 'SCHOOL_OF_DIVINATION', 'OOTDL_ACADEMY_PHILOSOPHER');

ALTER TABLE "Character" ALTER COLUMN "subclassName" TYPE "Subclasses" USING ("subclassName"::text::"Subclasses");

DROP TYPE "Subclasses_old";
